name: Python CI
on: [push]
jobs:
 build:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-24.04, ubuntu-22.04]
      python-version: [3.8, 3.12]
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - run: pip install -r requirements.txt
    - run: pytest
